In [1]:
import os 
print(os.getcwd())

/home/yuka/code/yukaberry/detect_ai_content/detect_ai_content/ml_logic/for_images


In [5]:
from tensorflow.keras.models import load_model

model = load_model('../../models/yukaberry/cnn_model.h5')
model.summary()

2024-11-04 18:26:46.965602: E external/local_xla/xla/stream_executor/cuda/cuda_driver.cc:152] failed call to cuInit: INTERNAL: CUDA error: Failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected


Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv2d_4 (Conv2D)               │ (None, 178, 178, 16)   │           448 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_4 (MaxPooling2D)  │ (None, 89, 89, 16)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_5 (Conv2D)               │ (None, 87, 87, 32)     │         4,640 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_5 (MaxPooling2D)  │ (None, 43, 43, 32)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_2 (Flatten)             │ (None, 59168)          │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 2)              │       118,338 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 123,431 (482.16 KB)

 Trainable params: 123,429 (482.14 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 2 (12.00 B)

In [6]:
from PIL import Image

In [8]:
from tensorflow.keras.preprocessing import image
import numpy as np

In [10]:
test_image = '0.jpg'
img = Image.open(test_image)
img.show()

In [9]:
def preprocess_image(img_path, target_size=(180, 180)):
    
    """
    Loads and preprocesses an image.

    Parameters:
    - img_path (str): Path to the image file.
    - target_size (tuple): Desired image size in pixels, e.g., (180, 180).

    Returns:
    - img_array (numpy.ndarray): Preprocessed image array ready for CNN input.
    """
    # Load the image with the target size and ensure it's RGB
    img = image.load_img(img_path, target_size=target_size, color_mode='rgb')
    
    # Convert the image to a numpy array
    img_array = image.img_to_array(img)
    
    # Optionally, expand dimensions to match the expected input shape for the model
    # (e.g., (1, 180, 180, 3) for a single image)
    img_array = np.expand_dims(img_array, axis=0)
    
    # Optionally, normalize the image data to [0, 1]
    img_array /= 255.0
    
    return img_array


In [12]:
pro_img = preprocess_image(test_image, target_size=(180, 180))
pro_img

array([[[[0.5254902 , 0.64705884, 0.83137256],
         [0.5254902 , 0.64705884, 0.83137256],
         [0.5254902 , 0.64705884, 0.83137256],
         ...,
         [0.52156866, 0.6117647 , 0.8745098 ],
         [0.52156866, 0.6117647 , 0.8745098 ],
         [0.52156866, 0.6117647 , 0.8745098 ]],

        [[0.5254902 , 0.64705884, 0.83137256],
         [0.5254902 , 0.64705884, 0.83137256],
         [0.5254902 , 0.64705884, 0.83137256],
         ...,
         [0.52156866, 0.6117647 , 0.8745098 ],
         [0.52156866, 0.6117647 , 0.8745098 ],
         [0.52156866, 0.6117647 , 0.8745098 ]],

        [[0.5254902 , 0.64705884, 0.83137256],
         [0.5254902 , 0.64705884, 0.83137256],
         [0.5254902 , 0.64705884, 0.83137256],
         ...,
         [0.52156866, 0.6117647 , 0.8745098 ],
         [0.52156866, 0.6117647 , 0.8745098 ],
         [0.52156866, 0.6117647 , 0.8745098 ]],

        ...,

        [[0.5372549 , 0.7019608 , 0.8       ],
         [0.5372549 , 0.7019608 , 0.8       ]

In [14]:
pred_class = model.predict(pro_img)
pred_class

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step


array([[0.49266428]], dtype=float32)

In [16]:
predicted_probabilities = np.argmax(pred_class, axis=1)
predicted_probabilities

array([0])

In [ ]:
# load model
# clean sample image data 
# predict 
# create api 
# test locap api 
# deploy locally 
# deploy to cloud 

In [2]:
import numpy as np
import tensorflow as tf
from tensorflow.keras import layers, models, metrics, callbacks, optimizers
from tensorflow.keras.models import Sequential
from tensorflow.keras.metrics import Precision, Recall, AUC

In [14]:
sample_data = 'sample/'
sample_ds = tf.keras.utils.image_dataset_from_directory(
  sample_data,
  labels='inferred',
  validation_split=0.2,
  subset="validation",
  seed=123,
  image_size=(180, 180),
  batch_size=64)

Found 2 files belonging to 2 classes.
Using 0 files for validation.


# NOTE : file structure has to Be 

- sample 
    - FAKE 
        - x.jpg
    - REAL 
        - xx.jpg 
        

In [15]:
# 0 likely representing 'FAKE' and 1 representing 'REAL'. 

sample_ds.class_names

['FAKE', 'REAL']

In [17]:
sample = []
sample_target = []

for images, labels in sample_ds:
    sample.append(images.numpy())
    sample_target.append(labels.numpy())
    
sample = np.concatenate(sample, axis=0)
sample_target = np.concatenate(sample_target)

2024-11-04 12:59:52.736597: I tensorflow/core/framework/local_rendezvous.cc:405] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence


In [18]:
sample.shape

(2, 180, 180, 3)

In [19]:
sample_target.shape

(2,)

In [1]:
sample_target

NameError: name 'sample_target' is not defined

In [22]:
sample = sample/255
sample

array([[[[0.00215302, 0.00244521, 0.00270665],
         [0.00215302, 0.00244521, 0.00270665],
         [0.00215302, 0.00244521, 0.00270665],
         ...,
         [0.00279892, 0.00269127, 0.0028143 ],
         [0.00279892, 0.00269127, 0.0028143 ],
         [0.00279892, 0.00269127, 0.0028143 ]],

        [[0.00215302, 0.00244521, 0.00270665],
         [0.00215302, 0.00244521, 0.00270665],
         [0.00215302, 0.00244521, 0.00270665],
         ...,
         [0.00279892, 0.00269127, 0.0028143 ],
         [0.00279892, 0.00269127, 0.0028143 ],
         [0.00279892, 0.00269127, 0.0028143 ]],

        [[0.00215302, 0.00244521, 0.00270665],
         [0.00215302, 0.00244521, 0.00270665],
         [0.00215302, 0.00244521, 0.00270665],
         ...,
         [0.00279892, 0.00269127, 0.0028143 ],
         [0.00279892, 0.00269127, 0.0028143 ],
         [0.00279892, 0.00269127, 0.0028143 ]],

        ...,

        [[0.00138408, 0.0012303 , 0.00109189],
         [0.00138408, 0.0012303 , 0.00109189]

In [23]:
model.predict(sample)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step


array([[0.49185356],
       [0.49184588]], dtype=float32)

In [25]:
model.predict(sample)[0][0]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step


np.float32(0.49185356)

# intepretation of result 

- A value close to 0 : a higher confidence that the image is 'FAKE'
- A value close to 1 : a higher confidence that the image is 'REAL'
- A value around 0.5 : the model is unsure and doesn’t lean strongly towards either class.


In [32]:
pred = float(model.predict(sample)[0][0])
pred

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step


0.4918535649776459

In [38]:
from io import BytesIO
sample_input = "sample/FAKE/0.jpg"

img = Image.open(BytesIO(sample_input))
img = sample_input/255
#img = sample_input.resize((180, 180))
print(img)
model.predict(img)

TypeError: unsupported operand type(s) for /: 'str' and 'int'